DROP TABLE IF EXISTS columns CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS users_to_tasks CASCADE;

CREATE TABLE columns (
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL
);


CREATE TABLE tasks (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    column_id INTEGER REFERENCES columns(id) ON DELETE CASCADE
);

CREATE TABLE users_to_tasks (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE
);